s1 = input("Nhập chuỗi s1: ")
s2 = input("Nhập chuỗi s2: ")
s3 = input("Nhập chuỗi s3: ")
index = int(input("Nhập index: "))
chieu_dai_s1 = len(s1)
chieu_dai_s2 = len(s2)
chieu_dai_s3 = len(s3)
s4 = s1[index:]
s2_lap_lai = s2 * 2
print("Chiều dài chuỗi s1 =", chieu_dai_s1)
print("Chiều dài chuỗi s2 =", chieu_dai_s2)
print("Chiều dài chuỗi s3 =", chieu_dai_s3)
print("Chuỗi con s4 được tạo ra từ chuỗi s1 =", s4)
print("Lặp lại chuỗi s2: 2 lần =", s2_lap_lai)
